import math

# game settings
RES = WIDTH, HEIGHT = 800, 450
# RES = WIDTH, HEIGHT = 1920, 1080
HALF WIDTH = WIDTH // 2
HALF HEIGHT = HEIGHT // 2
FPS = 0

PLAYER POS = 1.5, 5  # mini map
PLAYER ANGLE = 0
PLAYER SPEED = 0.004
PLAYER ROT SPEED = 0.022
PLAYER SIZE SCALE = 60
PLAYER MAX HEALTH = 100

MOUSE SENSITIVITY = 0.0003
MOUSE MAX REL = 40
MOUSE BORDER LEFT = 100
MOUSE BORDER RIGHT = WIDTH - MOUSE BORDER LEFT

FLOOR COLOR = (30, 30, 50)

FOV = math.pi / 3
HALF FOV = FOV / 2
NUM RAYS = WIDTH // 2
HALF NUM RAYS = NUM RAYS // 2
DELTA ANGLE = FOV / NUM RAYS
MAX DEPTH = 20

SCREEN DIST = HALF WIDTH / math.tan(HALF FOV)
SCALE = WIDTH // NUM RAYS

TEXTURE SIZE = 256
HALF TEXTURE SIZE = TEXTURE SIZE // 2
PLAYER_ATTACK_DAMAGE = 20